### ISSUE TITLE
Rust support for ntstrsafe.h inline functions

### ISSUE THREAD

**Issue by Xaeroxe** [microsoft/wdkmetadata#11]
https://learn.microsoft.com/en-us/windows-hardware/drivers/ddi/ntstrsafe/nf-ntstrsafe-rtlunicodestringinitex this API is missing. I think it's pretty easy to add but I'm not sure.

**Comment by mikebattista** [comment]
Everything in [ntstrsafe.h](https://github.com/microsoft/wdkmetadata/blob/main/generation/WDK/RecompiledIdlHeaders/km/ntstrsafe.h) appears to be inline functions, which aren't supported in the metadata.

Since Rust driver development is the target, should someone try to implement these natively in Rust?

**Comment by kennykerr** [comment]
We only support metadata-generated bindings. So, if there aren't any function exports then there's nothing here for `windows-rs` to consume. Developers are free to implement these in their own crates.

**Comment by kennykerr** [comment]
We can always reevaluate but at this point we have almost no WDK coverage to begin with. We need to get exports fleshed out and viable before considering additional hand-written APIs.

**Comment by rbtcollins** [comment]
The status on this could perhaps be changed to 'Closed' as I now see this available at `windows_sys::Wdk::Storage::FileSystem::RtlInitUnicodeStringEx` with feature Wdk_Storage_FileSystem enabled. Though its weird about the feature enabling it :). Thank you!
